name: checking gh project item-list

permissions: write-all

on:
  workflow_dispatch:
  push:
jobs:
  generate-chart:
    name: Generate chart
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
      - name: Get issues
        run: |
          gh auth status
          echo 'Getting Project issues issues count...'
          gh project item-list 4 --owner mpchenette --limit 10
