name: checking gh project item-list

permissions: write-all

on:
  workflow_dispatch:
  push:
jobs:
  generate-chart:
    name: Generate chart
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1150056
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get issues
        run: |
          gh auth status
          echo 'Getting Project issues issues count...'
          gh project item-list 3 --owner mpchenette
        env:
          TOKEN: ${{ secrets.CLASSIC_PAT }}
  