name: auth with a gh app

on:
  workflow_dispatch:
  push:

jobs:
  generate-chart:
    name: auth with a gh app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: 1150056
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - run: gh auth status
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - run: gh project item-list 3 --owner mpchenette
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
  