name: auth with a gh app

on:
  workflow_dispatch:
  push:

jobs:
  generate-chart:
    name: auth with a gh app
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1150056
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.CLASSIC_PAT }}

      - run: gh project item-list 3 --owner mpchenette
        env:
          GH_TOKEN: ${{ secrets.CLASSIC_PAT }}
  